version: "3.5"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db